# -*- coding: utf-8 -*-
"""Visualisasi Data Covid-19 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-uwJA9crmZz5F4j9K7VR6i17IAAtcjt
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("Data Covid19.csv")
data.head()

data.info()

data['Last Update'].unique()

latest_date = '28/02/2021 05.22'
data[data['Last Update']==latest_date]

unique_countries = data[data.Confirmed>0]['Country/Region'].unique()
unique_countries.sort()
unique_countries

country_confirmed_case = []
for i in unique_countries:
  country_confirmed_case.append(data[data.Confirmed>0][data['Country/Region']==i][data['Last Update']==latest_date].Confirmed.sum())

print(set(zip(unique_countries, country_confirmed_case)))

unique_provinces = data['Province/State'][data.Confirmed>1].unique()
unique_provinces

province_confirmed_case = []
for i in unique_provinces:
  province_confirmed_case.append(data[data.Confirmed>0][data['Province/State']==i][data['Last Update']==latest_date].Confirmed.sum())

print(set(zip(unique_provinces, province_confirmed_case)))

nan_indices = []
for i in range(len(unique_provinces)):
  if type(unique_provinces[i])==float:
    nan_indices.append(i)

unique_provinces = list(unique_provinces)
province_confirmed_case = list(province_confirmed_case)

for i in nan_indices:
  unique_provinces.pop(i)
  province_confirmed_case.pop(i)

unique_provinces

plt.barh(unique_countries, country_confirmed_case)
plt.show()

plt.figure(figsize=(50,40))
plt.barh(unique_provinces, province_confirmed_case)
plt.show()

plt.figure(figsize=(10,10))
plt.pie(country_confirmed_case)
plt.legend(unique_countries, loc='best')
plt.show()

plt.figure(figsize=(20,20))
plt.pie(province_confirmed_case)
plt.legend(unique_provinces, loc='best')
plt.show()